# Generated by Django 4.2.7 on 2023-11-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("group", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                ("fav_manufacturer", models.CharField(max_length=30)),
            ],
        ),
    ]
